image:
  name: gitlab.ewi.tudelft.nl:4242/cse3100/admin/docker-ci-image-builder@sha256:1eafab4f37ee34adc8093780d332b378fd579ca59bbfdfd110ed2f1f559dba08
  pull_policy: always

stages:
- build
- test

build:
  stage: build
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal v2-build exe:jq-clone

from-upstream:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test from-upstream

week3:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week3

week4:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week4