image:
  name: gitlab.ewi.tudelft.nl:4242/cse3100/admin/docker-ci-image-builder@sha256:7fb6c074546cd8c3422f3d7dae6dcb6240b14ac3d414fc97927bf8df71d322e8
  pull_policy: always

stages:
- build
- test

build:
  stage: build
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal v2-build exe:jq-clone

from-upstream:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test from-upstream

week3:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week3

week4:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week4