image: gitlab.ewi.tudelft.nl:4242/cse3100/admin/docker-ci-image-builder@sha256:0c8ec76dd1abab06c77f8cca015e8e69d487e3c8eb4487e1aa739aa8f5398a70


stages:
- build
- test

build:
  stage: build
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal v2-build exe:jq-clone

from-upstream:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test from-upstream

week3:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week3

week4:
  stage: test
  before_script:
  - cp -r ~/.cabal .
  - cp -r /dist-newstyle .
  - cabal v2-configure --enable-tests
  script:
  - cabal test week4